pd_scroll_to_top: 1
pd_sticky_sidebars: 1
pd_logo_light: themes/custom/em_magazine/branding/logo-light.svg
pd_logo_dark: themes/custom/em_magazine/branding/logo-dark.svg
pd_facebook: 'https://www.facebook.com/'
pd_twitter: 'https://twitter.com/'
pd_sticky_header: 1
pd_show_cart_button: 1
pd_show_search_button: 1
pd_show_hamburger_menu: 1
pd_search_button_text: Go
pd_search_field_placeholder_text: 'Search for...'
pd_teaser_uppercase_title: 0
pd_teaser_show_author_info: 1
pd_teaser_show_post_date: 1
pd_teaser_date_format: short
pd_mailchimp_signup_headline: ''
pd_mailchimp_signup_text: ''
pd_additional_css: ''
pd_custom_css_file: 0
pd_additional_head_javascript: ''
pd_additional_body_javascript: ''
_core:
  default_config_hash: k84OIv7-CT8_mgZ8exurDG9xgqFtic-_maMrre2vdVI
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
pd_google-plus: ''
pd_youtube: ''
pd_instagram: ''
pd_pinterest: ''
pd_tumblr: ''
pd_linked-in: ''
